title: "BLOG DE TECNOLOGÍA"
description: "Blog y proyectos tecnológicos"
baseurl: "/tecnologia-lozanos"
url: "https://johnylozano.github.io"

remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache